stages:
  - build
  - deploy

lint-and-test:
  stage: build
  tags:
    - tubes2wbd
  script:
    - 'npm cache clean'
    - 'sudo rm -rf node_modules'
    - 'npm install'
    - 'eslint src'
    - 'npm run test'

bankpro-deploy:
  stage: deploy
  tags:
    - tubes2wbd
  script:
    - bash aws-command.sh
  environment:
    - name: production
    - url: ec2-54-89-199-114.compute-1.amazonaws.com
