stages:
  - build
  - deploy

lint-test:
  stage: build
  tags:
    - tubes2wbd
  script:
    - 'whoami'
    - 'ls'
    - 'cd /home/ubuntu/bank-pro'
    - 'npm install'
    - 'eslint src'
    - 'npm run test'
