stages:
  - build
  - deploy

lint-and-test:
  stage: build
  tags:
    - tubes2wbd
  script:
    - 'pwd'
    # - 'sudo rm -rf node_modules'
    # - 'sudo npm install'
    # - 'eslint src'
    # - 'sudo npm run test'

bankpro-deploy:
  stage: deploy
  tags:
    - tubes2wbd
  script:
    - bash aws-command.sh
